### ISSUE TITLE
Is the configuration the same for spacemacs?

### ISSUE THREAD

**Issue by MicSokoli** [active-group/active-kondo#1]
I can't get this to work on spacemacs.

I am using `[active-clojure "0.27.0"]`.

I wasn't sure where to place this project, so I tried both, 
```
~/.clj-kondo
├── config.edn
└── hooks
    ├── monad.clj
    ├── reacl.clj
    └── record.clj
```
and
```
~/.clj-kondo
└── active-kondo
    ├── config.edn
    ├── hooks
    │   ├── monad.clj
    │   ├── reacl.clj
    │   └── record.clj
    └── README.md
```

I can tell that it's clj-kondo that is doing the checking because `flycheck-verify-checker` gives me
```
Syntax checker in buffer project.clj in clojure-mode:

  clj-kondo-clj
    - major mode: `clojure-mode' supported
    - may enable: yes
    - predicate:  t
    - executable: Found at /home/me/bin/clj-kondo

Flycheck can use this syntax checker for this buffer.

Flycheck Mode is enabled. Use M-m u C-c ! x to enable disabled checkers.
```
and because I can see that clj-kondo is creating a `.cache` directory with errors related to active-clojure code.
clj-kondo in emacs works through flycheck, as far as I can tell.

Not sure if I'm missing a step somewhere, or I need to use a different configuration approach for spacemacs.

**Comment by cresh** [comment]
> I can't get this to work on spacemacs.

What are you expecting to see? What do you actually see?

> I wasn't sure where to place this project, so I tried both,
> 
> ```
> ~/.clj-kondo
> ├── config.edn
> └── hooks
>     ├── monad.clj
>     ├── reacl.clj
>     └── record.clj
> ```

I am also using Spacemacs and this setup works for me.

**Comment by MicSokoli** [comment]
Right. 

Expected behaviour:
There should be not red squiggly lines coming from the linter on my emacs/spacemacs buffer that contains calls to `active.clojure.record/define-record-type`, specifically under the lines of code that represent the body of calls to this macro.

Actual behaviour: The red squiggly lines are there and the code appears wrong to the linter. The code runs fine, by the way.

For example
```
(define-record-type MyThing
  make-my-thing
  my-thing?
  [property my-thing-property])
```
has a red squiggly line under everything apart from `define-record-type`.

`flycheck-list-errors` gives me

```
 comma…    66  21 error           unresolved symbol MyThing (clj-kondo-clj)
 comma…    67   3 error           unresolved symbol make-my-thing (clj-kondo-clj)
 comma…    68   3 error           unresolved symbol my-thing? (clj-kondo-clj)
 comma…    69   4 error           unresolved symbol property (clj-kondo-clj)
 comma…    69  13 error           unresolved symbol my-thing-property (clj-kondo-clj)
```

**Comment by cresh** [comment]
What does `clj-kondo` output when you run it from the command line?
```
clj-kondo --lint <path-to-clj-file>
```

To be sure that `clj-kondo` picks up the correct configuration, you could also specifiy the path to the `.clj-kondo` directory that contains the checkout of `active-kondo`, in my case for example:

```
clj-kondo --config-dir ~/.clj-kondo --lint <path-to-clj-file>
```

**Comment by MicSokoli** [comment]
Running clj-kondo from the CLI like you described listed the same findings that I saw on spacemacs. 
The fix was to update my clj-kondo binary (I had a release from February 2020), and put the configuration in the following directory. I am running Debian buster.
```
~/.config
└── clj-kondo
	├── config.edn
	└── hooks
    	├── monad.clj
    	├── reacl.clj
    	└── record.clj
```
