### ISSUE TITLE
Support for `reacl-c`

### ISSUE THREAD

**Issue by neshtea** [active-group/active-kondo#3]
Since many or our libraries today either migrate to [`reacl-c`](https://github.com/active-group/reacl-c) or use it from the get-go, we should consider adding `reacl-c` macros to `active-kondo`.  After a quick investigation, there are eight macros in `reacl-c` (not including `reacl-c-basics` and `-testing`):

- `class`
- `defclass`
- `provided`
- `defdom`
- `ref-let`
- `state-validator`
- `defn-dom`
- `def-dom`

Two questions/tasks:

- which of these macros are considered public (as in 'users should use these macros') and which are private?
- for those we consider public, could we add rules for `clj-kondo` to `active-kondo`?

**Comment by dfrese** [comment]
Added quite a lot reacl-c related. Also fixed and extended define-record-type stuff.
